# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Termux ARM64 aapt2 override
android.nonFinalResIds=false
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2

# Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.jetifier.ignorelist=butterknife
org.gradle.console=verbose
