package com.trimettransit.tracker.ui.theme

import androidx.compose.ui.graphics.Color

// TriMet brand colors
val TrimetBlue = Color(0xFF0079C1)

// Light theme M3 tokens
val LightPrimary = Color(0xFF0079C1)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD6E8FF)
val LightOnPrimaryContainer = Color(0xFF001E31)
val LightSecondary = Color(0xFF4F5B71)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFDFCFF)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFDFCFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFE0E2EC)
val LightOnSurfaceVariant = Color(0xFF44474E)
val LightOutline = Color(0xFF74777F)
val LightInverseSurface = Color(0xFF2F3033)
val LightInverseOnSurface = Color(0xFFF2F0F4)
val LightInversePrimary = Color(0xFF9ECAFF)

// Dark theme M3 tokens
val DarkPrimary = Color(0xFF9ECAFF)
val DarkOnPrimary = Color(0xFF003352)
val DarkPrimaryContainer = Color(0xFF004C75)
val DarkOnPrimaryContainer = Color(0xFFD6E8FF)
val DarkSecondary = Color(0xFFBBC7DB)
val DarkOnSecondary = Color(0xFF213247)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A1C1E)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF1A1C1E)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF44474E)
val DarkOnSurfaceVariant = Color(0xFFC4C6D0)
val DarkOutline = Color(0xFF8E9099)
val DarkInverseSurface = Color(0xFFE2E2E6)
val DarkInverseOnSurface = Color(0xFF2F3033)
val DarkInversePrimary = Color(0xFF0079C1)
