package com.trimettransit.tracker.ui.theme

import androidx.compose.ui.graphics.Color

// TriMet brand colors
val TrimetBlue = Color(0xFF0079C1)
val TrimetBlueDark = Color(0xFF005A91)
val TrimetOrange = Color(0xFFFF7F00)

// Line colors
val CircleRed = Color(0xFFE60000)
val CircleBlue = Color(0xFF0000FF)
val CircleYellow = Color(0xFFFFDC00)
val CircleGreen = Color(0xFF00A300)
val CircleBlack = Color(0xFF000000)
val CircleDefault = Color(0xFF888888)

// Light theme M3 tokens
val LightPrimary = Color(0xFF0079C1)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD6E8FF)
val LightOnPrimaryContainer = Color(0xFF001E31)
val LightSecondary = Color(0xFF4F5B71)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD7E3F9)
val LightOnSecondaryContainer = Color(0xFF0C1D31)
val LightTertiary = Color(0xFFFF7F00)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDCCB)
val LightOnTertiaryContainer = Color(0xFF301400)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFDFCFF)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFDFCFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFE0E2EC)
val LightOnSurfaceVariant = Color(0xFF44474E)
val LightOutline = Color(0xFF74777F)
// Light M3 expressive surface tokens
val LightSurfaceBright = Color(0xFFFDFCFF)
val LightSurfaceDim = Color(0xFFDEDEE0)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF7F7FB)
val LightSurfaceContainer = Color(0xFFF1F1F5)
val LightSurfaceContainerHigh = Color(0xFFEBEBEF)
val LightSurfaceContainerHighest = Color(0xFFE5E5E9)
val LightInverseSurface = Color(0xFF2F3033)
val LightInverseOnSurface = Color(0xFFF2F0F4)
val LightInversePrimary = Color(0xFF9ECAFF)
val LightOutlineVariant = Color(0xFFC4C6D0)
val LightScrim = Color(0x52000000)


// Dark theme M3 tokens
val DarkPrimary = Color(0xFF9ECAFF)
val DarkOnPrimary = Color(0xFF003352)
val DarkPrimaryContainer = Color(0xFF004C75)
val DarkOnPrimaryContainer = Color(0xFFD6E8FF)
val DarkSecondary = Color(0xFFBBC7DB)
val DarkOnSecondary = Color(0xFF213247)
val DarkSecondaryContainer = Color(0xFF38495E)
val DarkOnSecondaryContainer = Color(0xFFD7E3F9)
val DarkTertiary = Color(0xFFFFB486)
val DarkOnTertiary = Color(0xFF4E2600)
val DarkTertiaryContainer = Color(0xFF703900)
val DarkOnTertiaryContainer = Color(0xFFFFDCCB)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A1C1E)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF1A1C1E)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF44474E)
val DarkOnSurfaceVariant = Color(0xFFC4C6D0)
val DarkOutline = Color(0xFF8E9099)
// Dark M3 expressive surface tokens
val DarkSurfaceBright = Color(0xFF404246)
val DarkSurfaceDim = Color(0xFF1A1C1E)
val DarkSurfaceContainerLowest = Color(0xFF0E0E11)
val DarkSurfaceContainerLow = Color(0xFF222427)
val DarkSurfaceContainer = Color(0xFF282A2D)
val DarkSurfaceContainerHigh = Color(0xFF333538)
val DarkSurfaceContainerHighest = Color(0xFF3E4043)
val DarkInverseSurface = Color(0xFFE2E2E6)
val DarkInverseOnSurface = Color(0xFF2F3033)
val DarkInversePrimary = Color(0xFF0079C1)
val DarkOutlineVariant = Color(0xFF44474E)
val DarkScrim = Color(0x52000000)
