package com.trimettransit.tracker.model

data class VehiclePosition(
    val vehicleID: Int = 0,
    val type: String = "",
    val blockID: Int = 0,
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val bearing: Float = 0f,
    val routeNumber: Int = 0,
    val direction: Int = 0,
    val tripID: String = "",
    val isNewTrip: Boolean = false,
    val delay: Int = 0,
    val signMessage: String = "",
    val signMessageLong: String = "",
    val nextLocID: Int = 0,
    val nextStopSeq: Int = 0,
    val lastLocID: Int = 0,
    val lastStopSeq: Int = 0,
    val serviceDate: Long = 0,
    val locationInScheduleDay: Int = 0,
    val time: Long = 0,
    val expires: Long = 0,
    val isInCongestion: Boolean = false,
    val loadPercentage: Int = 0,
    val garage: String = "",
    val extraBlockID: String = "",
    val isOffRoute: Boolean = false
)
